baseURL = "https://bingx.joinhelpers.com/"
languageCode = "ko-kr"
title = "BingX 媛??媛?대뱶 | JoinHelpers"
theme = "PaperMod"
enableRobotsTXT = true

[params]
  defaultTheme = "light"
  disableThemeToggle = true
  ShowReadingTime = false
  comments = false

[menu]
  [[menu.main]]
    name = "媛??諛⑸쾿"
    url = "/guide/register/"
    weight = 1
  [[menu.main]]
    name = "?댁슜 諛⑸쾿"
    url = "/guide/manual/"
    weight = 2
  [[menu.main]]
    name = "異붿쿇??蹂寃?
    url = "/referral-reset/"
    weight = 3
  [[menu.main]]
    name = "?대깽??
    url = "/event/"
    weight = 4
  [[menu.main]]
    name = "FAQ"
    url = "/faq/"
    weight = 5

[markup.goldmark.renderer]
  unsafe = true
